language: node_js

node_js: 8

env:
  global:
  - NODE_ENV=TEST

services:
- mysql

before_install:
- mysql -u root --password="" < test/travis.sql
- pushd client
- npm install
- npm run build
- popd

script:
- npm run test-int
- node server.js &
- npm run test-e2e
