language: node_js

node_js:
  - "iojs"
  - "7"

env:
  global:
    - TEST_DB_USERNAME=test
    - TEST_DB_PASSWORD=password
    - TEST_DB_NAME=spotifymainstream
    - TEST_DB_PORT=3306

services:
- mysql

before_install:
- mysql -u root --password="" < test/travis.sql