language: node_js

node_js: 8

env:
  global:
  - NODE_ENV=TEST

services:
- mysql

before_install:
- mysql -u root --password="" < test/travis.sql
- pushd client
- npm install
- popd

script:
- node server.js &
- npm run test-e2e-travis
- npm run test-int

os: linux

addons:
  chrome: stable

group: stable

dist: trusty

sudo: required